### ISSUE TITLE
isplit legalization breaks with basic blocks

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/cranelift#1159]
```
test compile
target x86_64

function u0:0(i128, i128, i64) -> i128 system_v {
                                ebb0(v0: i128, v1: i128, v2: i64):
                                    trap user0

                                ebb1:
@0005                               v17 = iconst.i128 0
@0006                               v20 = iconst.i128 0
@000a                               trap user0

                                ebb79:
@00dc                               v425 = iconst.i64 0
@00dc                               v426 = icmp_imm eq v425, 1
@00dc                               brnz v426, ebb80
@00dc                               jump ebb85(v20, v17)

                                ebb80:
@00e0                               trap user0

                                ebb85(v462: i128, v874: i128):
@00ed                               trap user0
}

**Comment by bjorn3** [comment]
```
thread 'main' panicked at 'Inserting instruction isplit after brnz, and before jump', cranelift-codegen/src/cursor.rs:650:33
stack backtrace:
[...]
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: <&mut cranelift_codegen::cursor::FuncCursor as cranelift_codegen::ir::builder::InstInserterBase>::insert_built_inst
             at cranelift-codegen/src/cursor.rs:650
  10: <cranelift_codegen::ir::builder::InsertBuilder<IIB> as cranelift_codegen::ir::builder::InstBuilderBase>::build
             at cranelift-codegen/src/ir/builder.rs:132
  11: cranelift_codegen::ir::builder::InstBuilder::Unary
             at ./target/debug/build/cranelift-codegen-b2c908af5b526fb8/out/inst_builder.rs:2485
  12: cranelift_codegen::ir::builder::InstBuilder::isplit
             at ./target/debug/build/cranelift-codegen-b2c908af5b526fb8/out/inst_builder.rs:2237
  13: cranelift_codegen::legalizer::split::split_value
             at cranelift-codegen/src/legalizer/split.rs:266
  14: cranelift_codegen::legalizer::split::perform_repairs
             at cranelift-codegen/src/legalizer/split.rs:192
  15: cranelift_codegen::legalizer::split::split_ebb_params
             at cranelift-codegen/src/legalizer/split.rs:161
  16: cranelift_codegen::legalizer::legalize_function
             at cranelift-codegen/src/legalizer/mod.rs:154
  17: cranelift_codegen::context::Context::legalize
             at cranelift-codegen/src/context.rs:265
  18: cranelift_codegen::context::Context::compile
             at cranelift-codegen/src/context.rs:144
  19: cranelift_codegen::context::Context::compile_and_emit
             at cranelift-codegen/src/context.rs:113
```

**Comment by bjorn3** [comment]
Another option would be to insert the isplit/iconcat before the the conditional jump.
