### ISSUE TITLE
Panic in SimpleJITRelocSink::reloc_jt

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/cranelift#789]
```
thread 'rustc' panicked at 'not yet implemented', /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/9094a3b/cranelift-simplejit/src/backend.rs:537:9
stack backtrace:
[...]
   8: std::panicking::begin_panic
             at /rustc/7cdaffd7962c4aae0cadd82baa241901b03f9458/src/libstd/panicking.rs:408
   9: <cranelift_simplejit::backend::SimpleJITRelocSink as cranelift_codegen::binemit::memorysink::RelocSink>::reloc_jt
             at /home/bjorn/.cargo/git/checkouts/cranelift-af8713b52459e6cd/9094a3b/cranelift-simplejit/src/backend.rs:537
[...]
```

<details>

```
test compile
set is_pic
target x86_64-unknown-linux-gnu

function u0:0() system_v {
; symbol _ZN21mini_core_hello_world4main17hdf273f44579fe5f2E
; instance Instance { def: Item(DefId(0:58 ~ mini_core_hello_world[317d]::main[0])), substs: [] }
; sig ([]; c_variadic: false)->()

; ssa {_4: (empty), _1: NOT_SSA, _5: (empty), _2: (empty), _3: (empty), _0: NOT_SSA}
; msg   loc.idx    param    pass mode            ssa flags  ty
; ret    _0      -          NoPass               NOT_SSA    ()

    ss0 = explicit_slot 8 ; _1: mini_core::Option<fn()> size=8 align=8,8
    gv0 = symbol colocated u1:8
    gv1 = symbol colocated u1:9
    gv2 = symbol colocated u1:10
    gv3 = symbol colocated u1:11
    sig0 = (i64) system_v
    sig1 = (i64) system_v
    sig2 = (i64) system_v
    fn0 = u0:2 sig0
    fn1 = colocated u0:1 sig1 ; Instance { def: Item(DefId(1:190 ~ mini_core[8787]::panic[0])), substs: [] }
    fn2 = u0:2 sig2
    jt0 = jump_table [ebb6, ebb3]

                                ebb0:
                                    v0 = stack_addr.i64 ss0
                                    jump ebb1

                                ebb1:
                                    nop 
; _1 = const main::FUNC_REF
@0000                               v1 = global_value.i64 gv0
@0000                               v2 = load.i64 aligned v1
@0000                               store aligned v2, v0
; _2 = discriminant(_1)
@0001                               v3 = load.i64 v0
@0001                               v4 = icmp_imm eq v3, 0
@0001                               v5 = iconst.i64 1
@0001                               v6 = iconst.i64 0
@0001                               v7 = select v4, v5, v6
; 
; switchInt(move _2)
@0001                               jump ebb7

                                ebb7:
@0001                               br_table.i64 v7, ebb2, jt0

                                ebb2:
@0001                               nop 
; 
; unreachable
@0002                               v8 = global_value.i64 gv1
@0002                               call fn0(v8)
@0002                               trap user65535

                                ebb3:
@0002                               nop 
; _3 = Not(const false)
@0004                               v9 = iconst.i8 0
@0004                               v10 = uextend.i32 v9
@0004                               v11 = icmp_imm eq v10, 0
@0004                               v12 = bint.i8 v11
; 
; switchInt(_3)
@0005                               v13 = uextend.i32 v12
@0005                               brz v13, ebb5
@0005                               jump ebb4

                                ebb4:
@0005                               nop 
; _5 = &(promoted[0]: (&str, &str, u32, u32))
@0006                               v14 = global_value.i64 gv2
; _4 = _5
; 
; const mini_core::panic(move _4)
@0007                               call fn1(v14)
@0007                               v15 = global_value.i64 gv3
@0007                               call fn2(v15)
@0007                               trap user65535

                                ebb5:
@0007                               nop 
; 
; goto
@0009                               jump ebb6

                                ebb6:
@0009                               nop 
; 
; return
@0002                               return
}
```

</details>

**Comment by lars-t-hansen** [comment]
That's probably a consequence of the things I did for jump tables.  I'll try to look into this later today.

**Comment by lars-t-hansen** [comment]
So the thing about the relocsink is, that `reloc_jt()` is now actually used by cranelift-codegen to indicate a location that must be fixed up if the code and the jump tables / rodata are moved apart.   Specifically, `jt_disp4()` in isa/x86/binemit.rs will call `sink->reloc_jt()`.

In the past, all the `reloc_jt()` implementations have just had an `unimplemented!()` body, as does the one in simplejit.  I left those in so that each implementation could decide for itself whether it should adapt to the change in binemit.

In the case of simplejit i'm guessing there's really no need to move the code and the jump tables / rodata apart (this is a thing spidermonkey needs to do to insert a custom epilogue), so the relocsink could just ignore the reloc.  I'll create a PR that implements that.

**Comment by lars-t-hansen** [comment]
cranelift-faerie has the same issue, btw -- not sure whether i should fix it there too?

**Comment by bnjbvr** [comment]
Can it be implemented in such a way that the default is the previous behavior, but this behavior can be overriden (for the Spidermonkey use case)? (This is possible by using a trait and providing a body to one of the trait methods, but I can't recall off the top of my head if this is using traits.)

**Comment by lars-t-hansen** [comment]
I don't know.  That seems unnecessarily complicated, actually, since the reloc is specific to x86 and specific to pc-relative data in the same vector as the code.  Backends that don't need to split those apart don't need to do anything for that reloc (but should still panic for other relocs, which are unexpected).

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/cranelift/pull/790 has been merged.
